/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


public class App {
    public static void main(String[] args) {
//        Quotes randomQuoteFromFile = new Quotes();
//        System.out.println("Qoute from file :"+ randomQuoteFromFile.readQuotesFromFile());




        Quotes.readQuotesFromApi();
//        Quotes.readQuotesFromApi();
//        Quotes.readQuotesFromApi();



    }



}

