/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


public class App {
    public static void main(String[] args) {
        System.out.println( "Qoute from local file "+Quote.readQuotes("app/src/main/resources/recentquotes.json"));





        System.out.println( "Qoute from API  "+Quotes.readQuotesFromApi());
//



    }



}

